## Request timeout
# timeout: 5s

## Uncomment following line in order to write template from scratch (be careful!)
#no_builtin_template: true

## Customizable templates path
#templates:
#  - contrib/templates/legacy/template.tmpl
templates:
   - /etc/prometheus-webhook-dingtalk/dingtalk/dingtalk.tmpl
## You can also override default template using `default_message`
## The following example to use the 'legacy' template from v0.3.0
#default_message:
#  title: '{{ template "legacy.title" . }}'
#  text: '{{ template "legacy.content" . }}'

## Targets, previously was known as "profiles"
targets:
  webhook:
    url: https://oapi.dingtalk.com/robot/send?access_token=fb03f457fb85e327c2d78f06cbe21ea1744cba5a2d12b7d3c64ea442275b43a6
    # secret for signature
    secret: SECc3fbde7d46366360a95625c2f126a746a3884ab8ab0448e9333af352190fbb41
    message:
      title: '{{ template "ding.link.title" . }}'
      text: '{{ template "ding.link.content" . }}'
